import type { Metadata } from "next";
import Head from 'next/head'
import 'material-symbols';
import { Playfair_Display, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";


const playfair = Playfair_Display({
  variable: "--playfair-display",
  subsets: ["latin"]
})

const plusjakarta = Plus_Jakarta_Sans({
  variable: "--plus-jakarta-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Bienvenido a Vivero La Cumbrecita",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="es-Ar" className={`${playfair.variable} ${plusjakarta.variable}`}>
      <Head>
        <link rel="preload" as="video" href="/viverovideo" type="video/mp4" />
      </Head>
      <body>
        <Header/>
        <main className="flex flex-col relative w-full pt-18 mt-4 bg-surface grow">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
