import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Plus_Jakarta_Sans } from "next/font/google";
import 'material-symbols';
import "./globals.css";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";


const playfair = Playfair_Display({
  variable: "--playfair-display",
  subsets: ["latin"]
})

const plusjakarta = Plus_Jakarta_Sans({
  variable: "--plus-jakarta-sans",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Bienvenido a Vivero La Cumbrecita",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="es-Ar" className={`${playfair.variable} ${plusjakarta.variable}`}>
      <body>
        <Header/>
        <main className="flex flex-col relative w-full pt-16 bg-[#DDD8B8] grow">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
